add subscribe and unsubscribe to message recieve
Northeastern-Electric-Racing/Siren pull request #18
Opened 2023-09-19 04:09 UTC by jr1221

closes #9 

leaves parsed JSON as `parsedMessage` available for future casting to `ServerData`

3 different behavior paths:
 - logs to console upon JSON parse error, the exits the message
 - silently continues to publish block if valid JSON doesn't contain necessary fields
 - exits the message after a correct JSON is used for sub/unsub

2023-09-19 17:45 UTC, evanlombardo requested changes
Great job, only thing you should change is to make `parsedMessage` of type `JSON` instead of `any`.

2023-09-19 18:04 UTC, evanlombardo commented
Have you done thorough testing on the `subscriptionMessage`? What happens if you make the argument something besides `subscribe` or `unsubscribe`? Or if the topics aren't the same as in the enum?

2023-09-19 18:22 UTC, jr1221 commented
If the argument field is present, but is wrong, it will still treat it like a subscription message but not sub/unsub to anything, but it will exit out.  
I didn't really know it should check topics, I will add code to validate that the topics given in the JSON are in the enum.  
In summary:
JSON invalid --> logs error and exits
JSON Keys wrong --> moves on to `publish`
JSON values wrong --> Ill make another commit for this: exits out of the block without sub/unsubing, logs error


In terms of the type of `parsedMessage`, `JSON.parse` returns `any` so I don't know if I can type it as anything before I cast it to `SubscriptionMessage`?

2023-09-19 18:31 UTC, jr1221 commented
We could introduce a module that type guards the JSON types, so everything is verified the correct type.  But that could add some overhead.

2023-09-19 18:32 UTC, evanlombardo commented
Yeah nvm because we cast it, type any is fine.

2023-09-20 00:00 UTC, evanlombardo approved these changes

2023-09-20 00:31 UTC, merged