Implement typeguarding with the typia library
Northeastern-Electric-Racing/Siren pull request #19
Opened 2023-09-22 20:11 UTC by jr1221

This uses the [typia](https://typia.io/docs/) compiletime type validation system to check the types of `SubcriptionMessage` and `ServerData` from `Odyssey-Base`.  It is currently in generation mode as bun seems to be a nonstandard typescript compiler.  Code generation should work for any future customizations of the above types.  

It works by reading the typia/templates files at build time and outputting the typia/generated.  The templates file takes the types from `Odyssey-Base`, re-exports them so they can be accessed in the same import as the typeguards, and creates a bunch of `const` functions that provide the type validation.  There are various types of such functions documented at the link above, basic comments are included with each one.  It is important we don't use `typia.is` imported from typia to type check as that is not size efficient.  Also we can eventually comment the ones we dont use out to reduce the binary size, which is about 700 lines right now.  Only using the `checkIs` for each type would only be about 40-50 lines.

Other features:
it can stringify (implemented) and parse (not implemented) more efficiently than the JSON namespace, so for publishing we may want to use that stringify.  
it can generate random objects, which may be useful for testing libraries.  
it can deep clone objects (not currently implemented).

This PR switches the `message` body to harness `checkIs`, but we may want to switch to validation to get good errors.

2023-09-25 19:01 UTC, evanlombardo requested changes
Great job, this is an amazing addition so I'm glad it worked out. Two quick things, see my other comment and also add typia's installation to the `install` script.

2023-09-26 01:49 UTC, jr1221 commented on siren/typia/templates/message.types.ts
> +
The `templates` directory is what I wrote to tell typia to generate validation, which goes in the `generated` directory which I did add to the gitignore.  So the file above is basically not used at runtime but still needed for compile time.

2023-09-26 01:53 UTC, jr1221 commented
>  also add typia's installation to the `install` script.
Should I just add `bun install` to the `install` script?  Because that should pull in everything listed in `package.json` which includes `bun-types` and all of `typia` and its dependencies.

2023-09-26 05:35 UTC, evanlombardo commented
> > also add typia's installation to the `install` script.
> 
> Should I just add `bun install` to the `install` script? Because that should pull in everything listed in `package.json` which includes `bun-types` and all of `typia` and its dependencies.
> 
> Edit: [link to docs](https://bun.sh/docs/cli/install#bun-install)

Sounds good

2023-09-26 15:22 UTC, jr1221 commented
For some reason that doesn't work for me.  I committed it nonetheless maybe its a problem with my machine.  We could always look at it later.

2023-09-26 17:06 UTC, evanlombardo approved these changes

2023-09-26 17:19 UTC, merged